language: go

go:
  - "1.13.x"
  - "1.14.x"

script:
  - go get -u golang.org/x/lint/golint
  - make lint
  - go get github.com/stretchr/testify github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only
  - ./test.sh
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
